apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m0s
  path: app/frontend
  prune: false
  sourceRef:
    kind: GitRepository
    name: example-cloud-app
