apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: example-cloud-app
  path: crossplane
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-provider-stackit
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: crossplane
  sourceRef:
    kind: GitRepository
    name: example-cloud-app
  path: crossplane/provider-stackit
  prune: true
