apiVersion: postgresflex.stackit.cloud/v1alpha1
kind: Instance
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  forProvider:
    acl:
    - 0.0.0.0/0
    backupSchedule: 00 00 * * *
    flavor:
      cpu: 2
      ram: 4
    name: notebook
    projectId: 49d2999f-e391-4c14-98be-8f516d38e313
    replicas: 1
    storage:
      class: premium-perf2-stackit
      size: 5
    version: "16"

---
apiVersion: postgresflex.stackit.cloud/v1alpha1
kind: User
metadata:
  labels:
    app: notebook
  name: notebook
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        app: notebook
    projectId: 49d2999f-e391-4c14-98be-8f516d38e313
    roles:
    - createdb
    - login
    username: notebook
  writeConnectionSecretToRef:
    namespace: default
    name: notebook-db-creds

