apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  namespace: default
  labels:
    app: notebook
spec:
  selector:
    matchLabels:
      app: notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: reg3.infra.ske.eu01.stackit.cloud/example/cloud-app
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: notebook-db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: notebook-db-creds
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notebook-db-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notebook-db-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: notebook-db-name
                  key: name
          ports:
            - containerPort: 8080
              name: http
