apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  namespace: default
  labels:
    app: notebook
spec:
  selector:
    matchLabels:
      app: notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        env:
        - name: CONNECTION_STR
          valueFrom:
            secretKeyRef:
              name: notebook
              key: attribute.uri
        ports:
        - containerPort: 8080
          name: http

