apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: appdemo.project212a.runs.onstackit.cloud
  name: notebook
  namespace: default
spec:
  selector:
    app: notebook
  type: LoadBalancer
  ports:
  - name: notebook
    port: 8080

